language: cpp

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - MODE=LINUX
    - os: linux
      env:
        - MODE=ARDUINO

before_install:
    - if [ "$MODE" = "LINUX" ]; then eval "${MATRIX_EVAL}"; fi
    - if [ "$MODE" = "ARDUINO" ]; then source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh); fi
    - if [ "$MODE" = "ARDUINO" ]; then wget https://github.com/thelsing/FlashStorage/archive/master.zip; fi
    - if [ "$MODE" = "ARDUINO" ]; then sudo mkdir -p /usr/local/share/arduino/libraries/FlashStorage; fi
    - if [ "$MODE" = "ARDUINO" ]; then sudo unzip master.zip -d /usr/local/share/arduino/libraries/FlashStorage; fi
install:
  - if [ "$MODE" = "ARDUINO" ]; then arduino --install-library "WiFiManager"; fi
script:
     - if [ "$MODE" = "LINUX" ]; then cd knx-linux; fi
     - if [ "$MODE" = "LINUX" ]; then mkdir -p build; fi
     - if [ "$MODE" = "LINUX" ]; then cd build; fi
     - if [ "$MODE" = "LINUX" ]; then cmake ..; fi 
     - if [ "$MODE" = "LINUX" ]; then make; fi
     - if [ "$MODE" = "ARDUINO" ]; then arduino --verify --board arduino:samd:arduino_zero_native $PWD/examples/knx-demo/knx-demo.ino; fi
     
notifications:
  email:
    on_success: change
    on_failure: change
