language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - MODE=LINUX
    - os: linux
      env:
        - MODE=ARDUINO

before_install:
    - eval "${MATRIX_EVAL}"
script:
     - if [ "$MODE" = "LINUX" ]; then cd knx-linux; fi
     - if [ "$MODE" = "LINUX" ]; then mkdir -p build; fi
     - if [ "$MODE" = "LINUX" ]; then cd build; fi
     - if [ "$MODE" = "LINUX" ]; then cmake ..; fi 
     - if [ "$MODE" = "LINUX" ]; then make; fi
