language: cpp

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - MODE=LINUX
    - os: linux
      env:
        - MODE=ARDUINO

before_install:
    - if [ "$MODE" = "LINUX" ]; then eval "${MATRIX_EVAL}"; fi
    - if [ "$MODE" = "ARDUINO" ]; then source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh); fi
install:
  - if [ "$MODE" = "ARDUINO" ]; then arduino --install-library "WiFiManager"; fi
script:
     - if [ "$MODE" = "LINUX" ]; then cd knx-linux; fi
     - if [ "$MODE" = "LINUX" ]; then mkdir -p build; fi
     - if [ "$MODE" = "LINUX" ]; then cd build; fi
     - if [ "$MODE" = "LINUX" ]; then cmake ..; fi 
     - if [ "$MODE" = "LINUX" ]; then make; fi
     - if [ "$MODE" = "ARDUINO" ]; then build_platform esp8266; fi
